on:
  pull_request:
    branches:
      - live-ronit
    types: [closed]
name: 🚀 Deploy Website to Live Ronit Branch on pull request
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.LIVE_RONIT_SERVER }}
          username: ${{ secrets.LIVE_RONIT_USERNAME }}
          password: ${{ secrets.LIVE_RONIT_PASSWORD }}
          state-name: ./laravel-sync-state.json
